# -*- coding: utf-8 -*-
"""app_config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SEOX2HEy7eLmSycZTQewx6L6gRw-N-CJ
"""

## should be called app_config.py
from pathlib import Path
import os
import sys

if getattr(sys, 'frozen', False):
    # Running as a bundled executable
    BASE_DIR = os.path.dirname(sys.executable)
else:
    # Running in development (as a script)
    BASE_DIR = os.path.abspath(os.path.dirname(__file__))
    print('hi dis da base dir '+BASE_DIR)
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
# gives the folder that the app is in

# Simple: just use absolute paths to the parent directory
PROJECT_PARENT = os.path.abspath(os.path.join(BASE_DIR, ".."))
GRAPHICS_EXCELS_DIR = os.path.join(PROJECT_PARENT, "graphicsExcels")

IMAGES_DIR = os.path.join(PROJECT_PARENT, "goodimages")

IMG_EXTS = ('.png', '.jpg', '.jpeg', '.avif')  # used for quick validation
FALLBACK_IMAGE = os.path.join(ASSETS_DIR,'blank_square.png')
HEADER_PATH = os.path.join(ASSETS_DIR,'newgolden_header.png')
BHEADER_PATH = os.path.join(ASSETS_DIR,'newgolden_bottomheader.png')

FONT_PATH_CN = os.path.join(ASSETS_DIR,'NotoSansSC-SemiBold.ttf')
FONT_PATH_EN = os.path.join(ASSETS_DIR,'NotoSansSC-SemiBold.ttf')
FONT_PATH_BOLD = os.path.join(ASSETS_DIR,'Shrikhand-Regular.ttf')
#PRICEBOX_PATH = os.path.join(ASSETS_DIR,'pop_speech_bubb.png')
PRICEBOX_PATH = os.path.join(ASSETS_DIR,'yellowredspike.png')
FILLER_PATH = os.path.join(ASSETS_DIR,'blank_square.png')

# You can add other paths or settings here as well